### ISSUE TITLE
no provides method

### ISSUE THREAD

**Issue by academy-jtran** [jdmundrawala/windows-sdk-cookbook#5]
Using chef-client 11.12.8, I get the following problem:
# 
# Recipe Compile Error in d:/chef/cache/cookbooks/windows-sdk/libraries/windows_sdk_feature.rb
## NoMethodError

undefined method `provides' for WindowsSdkCookbook::Provider:Class
## Cookbook Trace:

  d:/chef/cache/cookbooks/windows-sdk/libraries/windows_sdk_feature.rb:49:in `<class:Provider>'
  d:/chef/cache/cookbooks/windows-sdk/libraries/windows_sdk_feature.rb:48:in`class:WindowsSdkCookbook'
  d:/chef/cache/cookbooks/windows-sdk/libraries/windows_sdk_feature.rb:1:in `<top (required)>'
## Relevant File Content:

d:/chef/cache/cookbooks/windows-sdk/libraries/windows_sdk_feature.rb:

 42:            :kind_of => [String]
 43:          )
 44:        end
 45:      end
 46:    end
 47:
 48:    class Provider < Chef::Provider
 49>>     provides :windows_sdk_feature, os: "windows"
 50:
 51:      def whyrun_supported?
 52:        true
 53:      end
 54:
 55:      def load_current_resource
 56:        versions = new_resource.features.map do |f|
 57:          WindowsSdkCookbook::Helpers.validate_feature!(f)
 58:

Running handlers:
[2015-07-02T12:24:06-06:00] ERROR: Running exception handlers
Running handlers complete
[2015-07-02T12:24:06-06:00] ERROR: Exception handlers complete
[2015-07-02T12:24:06-06:00] FATAL: Stacktrace dumped to d:/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 36.625533 seconds
[2015-07-02T12:24:06-06:00] FATAL: NoMethodError: undefined method `provides' for WindowsSdkCookbook::Provider:Class

**Comment by clintoncwolfe** [comment]
Works OK under chef 12.4.1; should probably narrow down the version in which 'provides' was introduces, and add a version constraint.

**Comment by jaym** [comment]
Thanks for the heads up, I'll add the version constraint. It should work with 12.3 as well.
